<?php

namespace AppBundle\Repository;

/**
 * AttributValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributValueRepository extends \Doctrine\ORM\EntityRepository
{
}
