<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTreeView(\AppBundle\Entity\Product $product )
    {
        $elements =  $this->getEntityManager()->getRepository('AppBundle:Category')->findAll(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        $arrayCollection = array();

        foreach($elements as $item) {
            $arrayCollection[] = array(
                'id' => $item->getId(),
                'text' => $item->getName(),
                'population' => true,
                'parent_id' => $item->getParent() !== null ? $item->getParent()->getId() : 0,
                "checked" => $item->getProducts()->contains($product) ? true : false
            );
        }
        return $this->getresultTree($arrayCollection);
        
    }

    private function getresultTree(array $elements, $parentId = 0) {
        
        $branch = array();
        
        foreach ($elements as $element) {
            if ($element['parent_id'] == $parentId) {            
                
                $children = $this->getresultTree($elements, $element['id']);
                if ($children) {
                   
                    $element['children'] = $children;
                   
                }
                $branch[] = $element;
            }
        }

        return $branch;
    }
}
