<?php

namespace AppBundle\Repository;

/**
 * StorageDepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageDepotRepository extends \Doctrine\ORM\EntityRepository
{
}
