parameters:
    #JWT Authentication
    jwt_private_key_path: "%kernel.project_dir%/var/jwt/private.pem"   # ssh private key path
    jwt_public_key_path:  "%kernel.project_dir%/var/jwt/public.pem"    # ssh public key path
    jwt_key_pass_phrase:  'ihsa2021'                                   # ssh key pass phrase
    jwt_token_ttl:        3153600000
    # Nelmio CORS
    cors_allow_origin: '*'                                             # API Allow Origin
    # Nelmio API DOC
    api_name: 'STYLE DE VIE API Documentation'                                 # API Name
